import { modeller } from "./modeller";
const model = new modeller.ModelBuilder();
model.add("Id",new modeller.Single(Guid));
model.add("Email","string");
model.validator("Email","required",undefined);
model.add("EmailConfirmed","boolean");
model.add("LockoutEnabled","boolean");
model.add("LockoutEnd",new modeller.Single(Date));
model.add("Fleets",new modeller.List(Fleet));
model.add("Role",new modeller.Single(Role));
model.add("FirstName","string");
model.validator("FirstName","required",undefined);
model.validator("FirstName","minlength",3);
model.validator("FirstName","maxlength",30);
model.add("LastName","string");
model.validator("LastName","required",undefined);
model.validator("LastName","minlength",3);
model.validator("LastName","maxlength",30);
model.add("IssuingAuthorityId",new modeller.Single(Guid));
model.add("LastLoggedIn",new modeller.Single(Date));
model.add("InActiveFor","number");
export const User = model.create();